### ISSUE TITLE
Server Exception With StatKilledByBear

### ISSUE THREAD

**Issue by Desymoo** [Mad-Gnome/vintage_story_leaderboard#1]
**Side**: Server
**Mod Version**: v1.1.1
**Game Version**: v1.19.7
**Some Extra Details**:
This is the only server exception I've experienced from the mod so far, specifically relating to the bear stat.
The same player threw this exception twice, the second time after respawning and returning to the same spot.
They claim that they didn't die to a bear and that there wasn't actually a bear anywhere nearby but I'd take that with a grain of salt.

Here's the full error report:
```
Exception: Object reference not set to an instance of an object.
   at scoreboard.StatKilledByBear.OverrideCB(Entity entity, DamageSource damageSource) in vintage_story_scoreboard\scoreboard_new\killedByBear.cs:line 50
   at Vintagestory.API.Common.Entities.Entity.Die(EnumDespawnReason reason, DamageSource damageSourceForDeath) in VintagestoryApi\Common\Entity\Entity.cs:line 1706
   at Vintagestory.API.Common.EntityAgent.Die_Patch1(EntityAgent this, EnumDespawnReason reason, DamageSource damageSourceForDeath)
   at Vintagestory.API.Common.EntityPlayer.Die(EnumDespawnReason reason, DamageSource damageSourceForDeath) in VintagestoryApi\Common\Entity\EntityPlayer.cs:line 1176
   at Vintagestory.GameContent.EntityBehaviorHealth.OnEntityReceiveDamage_Patch1(EntityBehaviorHealth this, DamageSource damageSource, Single& damage)
   at Vintagestory.API.Common.Entities.Entity.ReceiveDamage(DamageSource damageSource, Single damage) in VintagestoryApi\Common\Entity\Entity.cs:line 813
   at Vintagestory.API.Common.EntityAgent.ReceiveDamage_Patch2(EntityAgent this, DamageSource damageSource, Single damage)
   at Vintagestory.API.Common.CollectibleObject.tryEatStop_Patch3(CollectibleObject this, Single secondsUsed, ItemSlot slot, EntityAgent byEntity)
   at Vintagestory.API.Common.CollectibleObject.OnHeldInteractStop(Single secondsUsed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel) in VintagestoryApi\Common\Collectible\Collectible.cs:line 1351
   at Vintagestory.Server.ServerSystemInventory.HandleHandInteraction(Packet_Client packet, ConnectedClient client) in VintagestoryLib\Server\Systems\Inventory.cs:line 252
   at Vintagestory.Server.ServerMain.ProcessNetMessage(NetIncomingMessage msg, NetServer mainSocket) in VintagestoryLib\Server\ServerMainNetworking.cs:line 138
```

**Comment by Mad-Gnome** [comment]
The scoreboard was missing a section for killedbybear, I'm not sure if this caused this or not but it is in the mod now.
